env:
  browser: true
  es2021: true
root: true
extends:
  - '@gabrielyotoo/eslint-config-react-native'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
ignorePatterns: ['*.config.js']
plugins:
  - '@typescript-eslint'
  - react
  - eslint-plugin-react-hooks
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
rules:
  'import/order':
    [
      'error',
      {
        pathGroups:
          [
            { pattern: '@app/**', group: 'internal' },
            { pattern: '@screens/**', group: 'internal' },
            { pattern: '@components/**', group: 'internal' },
            { pattern: '@assets/**', group: 'internal', position: 'after' },
          ],
        groups: [['external', 'builtin'], 'internal', 'parent', 'sibling'],
        'newlines-between': 'always',
        pathGroupsExcludedImportTypes: ['internal'],
        alphabetize: { order: 'asc', caseInsensitive: true },
      },
    ]
  '@typescript-eslint/no-misused-promises':
    [2, { 'checksVoidReturn': { 'attributes': false } }]
